# Generated by Django 5.0 on 2023-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('mailAdress', models.CharField(max_length=100, null=True)),
                ('photoLink', models.CharField(max_length=155, null=True)),
            ],
        ),
    ]
