# Generated by Django 5.0 on 2023-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mailAdress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
